checkout.tip.suggestions=50,100,200
app.default.payment-method-id=1

spring.application.name=FoodApp
spring.datasource.url=jdbc:postgresql://dbUrl:5432/flavorfusion
spring.datasource.username=admin
spring.datasource.password=databasePass
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA configurations (optional, but commonly used with databases)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# RabbitMQ
spring.rabbitmq.host=172.16.0.5
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=rabbitMqPassword

secreteJwtString=Standard Secret Key you can find this online or generate yourself

# Mail server configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=youremail@gmail.com
spring.mail.password=aaaa aaaa aaaa aaaa
spring.mail.properties.mail.smtp.auth=trueenu
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


#AWS CONFIG
aws.s3.bucket=flavior-fusion-s3-bucket 
aws.s3.region=eu-north-1
aws.accessKeyId=acesskeyString
aws.secretKey=secretKey
aws.cloudfront.domain=https://d3u269mlo8clta.cloudfront.net

#IMAGE FILE SIZE

spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=1MB


#LOCAL REACT FRONTEND
base.payment.link=http://localhost:3000/pay?orderid=
fonntend.base.url=http://localhost:3000

spring.threads.virtual.enabled=true

#Redis
spring.data.redis.host=172.16.0.5
spring.data.redis.port=6379
spring.cache.type=none
spring.data.redis.password=redis
#spring.cache.redis.time-to-live=3600000


#google maps
google.maps.api.key=apiKey

#pok
pok.api.baseUrl=https://api-staging.pokpay.io/
pok.api.keyId=apikeyString
pok.api.keySecret=apikeySecretString
pok.api.merchantId=merchantId
pok.expiersAfterMinutes=40

#pok redirects
pok.redirectUrl=http://localhost:5173/paymentStatus/paymentSuccess
pok.failRedirectUrl=http://localhost:5173/paymentStatus/paymentFailed
pok.webhookUrl=https://bdb5-91-230-254-114.ngrok-free.app/api/v1/payments/webhook


server.error.include-message=always
#spring.jpa.show-sql=true
## Format the SQL for better readability (optional but recommended)
#spring.jpa.properties.hibernate.format_sql=true

app.internal-job-secret=INTERNAL_JOB_SECRET 

#spring.profiles.active=import_url

#spring.profiles.active=dev

ors.matrix.url=http://url:8082/ors/v2/matrix/driving-car

server.shutdown=graceful
